/* eslint-disable max-len */

import { getRandomValueFromArray } from './getRandomValueFromArray'


const prompts = [
	'A Mongol horse archer galloping across the open plains, bow drawn and ready to strike.',
	'A Renaissance artist painting in his candle-lit studio, surrounded by unfinished masterpieces.',
	'A Viking warrior leading a charge on a burning village, axe raised in fury.',
	'A World War II fighter pilot in a cockpit, diving through flak-filled skies.',
	'A battle-worn elven warrior standing on a battlefield littered with broken weapons and glowing magical remnants.',
	'A battle-worn trench medic carries a plasma defibrillator, recharging wounded exosuits during heavy bombardment.',
	'A biotech priest plants glowing soul-seeds in a gravity-free garden aboard a sacred orbital monastery.',
	'A bounty hunter tracks a shapeshifter through the desert, its form shifting between coyote, man, and rattlesnake spirit.',
	'A clockwork phoenix erupts from a steampunk forge, trailing fire and ash over a city of brass, steam, and rebellion.',
	'A colossal ring world stretching into the distance, its surface covered in futuristic cities and forests.',
	'A colossal sea serpent attacking a wooden Viking ship in a raging storm.',
	'A colossal spaceship drifts through a nebula, its metallic hull glowing with the reflection of cosmic gases.',
	'A cosmic deity emerging from a swirling vortex, its form shifting between energy and matter.',
	'A cosmic storm engulfing a space station, plasma tendrils ripping through metal and glass.',
	'A courier on a monocycle speeds through sniper fire, carrying a micro-reactor key needed to shut down a war machine.',
	'A covert team dives into a flooded bunker where bio-mechanical experiments grow inside glass tanks lit by eerie green glow.',
	'A covert unit steals a prototype invisibility cloak from a lab deep inside a volcano guarded by mech-powered flamethrowers.',
	'A crew of space pirates battling a federation fleet in the asteroid belt, debris and laser fire filling the void.',
	'A cursed sheriff\'s star brands its wearer with vengeance, granting immortality until every outlaw in the county is dead.',
	'A cyber-spirit trapped in an old telegraph wire possesses morse machines, transmitting messages from the dead to the living.',
	'A cybernetic angel descends through acid rain, spreading neon wings over a decaying megacity of chrome and ash.',
	'A cybernetic bounty hunter in a trench coat stands atop a neon-lit skyscraper, surveying a futuristic cityscape.',
	'A cyberpunk detective investigates a murder inside a hacked VR realm, where reality fractures with each new clue found.',
	'A cyberpunk samurai wielding an energy katana, engaged in battle with a towering AI-controlled mech in a dystopian Tokyo.',
	'A deep-space mining station orbits a rogue planet, with asteroid fragments colliding around it.',
	'A desert baron rides a mech-horse forged from meteor metal, hunting starborn creatures that drink moonlight and vanish.',
	'A dieselpunk war-rig rumbles through the badlands, driven by revenants bound to the vehicle until their debts are paid.',
	'A double agent in a trench coat trades secrets in a rain-slick alley, under flickering steam-lamps and mechanical eyes.',
	'A drifter with a lightning rod arm fights sand wraiths near a ghost town, his revolver firing electrified silver rounds.',
	'A floating saloon hovers above the desert on diesel thrusters, staffed entirely by clockwork bartenders and drunk ghosts.',
	'A forgotten cyber-temple lies deep underwater, protected by ancient robotic krakens and coral-coded security glyphs.',
	'A futuristic gladiator battle in an intergalactic arena, with alien spectators cheering.',
	'A futuristic soldier in a sleek exosuit, leaping between crumbling skyscrapers in a post-apocalyptic cyber-city.',
	'A ghost ship floats in space, its crew eternally reliving their last moments, trapped by an onboard AI’s sorrowful loop.',
	'A glitch-shaman reads fate through quantum patterns in the sky, guiding pilgrims through a technospiritual wasteland.',
	'A glowing city is powered by human dreams, harvested each night by quiet AI harvesters moving like shadows through beds.',
	'A group of explorers in the 1800s uncovering a lost temple in the dense Amazon jungle.',
	'A group of rebels hacking into a government surveillance hub in a cyber-dystopia, screens glowing ominously.',
	'A gunslinger duels a demon at high noon, shadows stretching unnaturally as the sky turns red and the wind whispers curses.',
	'A haunted AI core lies dormant beneath Martian sands, whispering the secrets of its creators into the red wind.',
	'A haunted deep-space observatory drifts in silence, echoing the cries of long-lost astronomers trapped in time loops.',
	'A haunted saloon replays a ghostly massacre every night, with phantoms stuck in a loop of bullets, poker, and betrayal.',
	'A hidden village deep within an enchanted forest, where glowing mushrooms light the pathways.',
	'A humanoid robot playing chess against a shadowy figure in a dimly lit cyber-noir café.',
	'A hyper-advanced alien civilization with crystalline structures and floating platforms above an ocean planet.',
	'A kingdom built upon the back of a titanic moving creature, its walls blending with the beast\'s body.',
	'A knight clad in golden armor confronts a dragon of stardust above a cosmic canyon lit by nebulae and falling comets.',
	'A living starship crafted from enchanted wood and dragon bone sails between realms, guided by arcane stellar charts.',
	'A lone astronaut staring at a massive black hole from the edge of a crumbling space station.',
	'A lone cyborg samurai wanders a rust desert of fallen machines, haunted by ghost-echoes of old battles and lost honor.',
	'A lone scavenger in a bulky space suit, salvaging wreckage from an abandoned space station orbiting Saturn.',
	'A mad tinkerer\'s steam-powered coffin-walker digs through graveyards, seeking lost limbs for its stitched-together master.',
	'A magical library with floating books and staircases that shift in midair.',
	'A magical train glides across the vacuum of space, its arcane steam engine puffing stardust and dreams into the void.',
	'A massive gear-driven walker crushes barbed wire as it storms a fortified bunker defended by robotic sentries.',
	'A massive holographic whale drifts through the skies of Neo-Tokyo, its translucent form humming with digital energy.',
	'A massive railgun embedded in a mountain opens fire on a steampunk dreadnought flying under the cover of a thunderstorm.',
	'A massive space ark carrying the last remnants of humanity, traveling through an endless cosmic expanse.',
	'A massive turtle drifts through space, carrying cities on its shell as it navigates gas rivers and nebular storms.',
	'A mechanical dragon with steam-powered wings circles above a brass city, gears churning beneath its burning metal skin.',
	'A medieval alchemist in a cluttered workshop, experimenting with glowing potions.',
	'A medieval army raises shields as orbital pods fall from the sky, releasing shock troopers clad in glowing battle suits.',
	'A medieval knight stepping through a glowing portal into a futuristic city.',
	'A memory hacker dives into corrupted minds, surfing glitchwave memories to find lost secrets inside others’ pasts.',
	'A mighty dragon perched atop a ruined castle, breathing fire into the stormy night sky.',
	'A moon-sized AI broadcasts poetry in light pulses, its verses echoing across space and reaching lonely starfarers.',
	'A mysterious deep-space probe encountering a massive, ancient alien structure floating in the void.',
	'A necromancer summoning an army of spectral warriors in a graveyard under a blood-red moon.',
	'A neon-lit cathedral orbits Jupiter, where robotic monks chant binary code beneath glowing stained-glass data panels.',
	'A neon-lit highway in a cyberpunk city, with hoverbikes racing between towering buildings.',
	'A phoenix rising from golden flames, its wings spreading embers across the sky.',
	'A pirate radio ship beams forbidden music through stardust, evading galactic enforcers by hiding in wormhole echoes.',
	'A plague ship locked in orbit weeps biological tendrils, its infected AI still trying to complete its original mission.',
	'A poker game between angels and devils decides the fate of a town, the stakes raised with every card turned in silence.',
	'A possessed mech fights divine drones in a ruined cathedral, its every strike echoing with hellfire and sacred hymns.',
	'A powerful AI controlling an entire city, its holographic face projected over a sprawling metropolis.',
	'A powerful wizard casting a spell, his hands crackling with raw arcane energy.',
	'A preacher with a cursed Bible summons spectral fire from the heavens to smite undead outlaws during a dust storm standoff.',
	'A preacher\'s organ in a remote chapel doubles as a sonic weapon, blasting banshees with holy vibrations during sermons.',
	'A prospector digs too deep and awakens a buried deity, now whispering in his mind and turning gold to blackened bone.',
	'A quantum library rearranges itself for each visitor, the books whispering paradoxes in languages that never existed.',
	'A quantum rift tearing open the sky above a city, revealing glimpses of parallel dimensions.',
	'A railroad built by the dead stretches endlessly westward, each track laid by a phantom worker bound to unfinished work.',
	'A reptilian alien royal family boards a living starship, its interior walls pulsing with warm light and rhythmic breath.',
	'A resistance fighter wields a steam-blade in close quarters aboard a hijacked train powered by nuclear fusion boilers.',
	'A retro-futuristic rocket ship launching from a sleek, utopian city in the 1950s vision of the future.',
	'A robot monk meditates under cherry blossoms on a floating island temple, decoding enlightenment from quantum signals.',
	'A robotic blacksmith hammers molten plasma into swords inside a volcanic forge fueled by solar flares and asteroid cores.',
	'A robotic explorer discovering an ancient alien temple on a desolate moon, glowing runes etched into the stone.',
	'A rogue AI constructing a massive Dyson sphere around a dying star.',
	'A rogue spy infiltrates a Nazi zeppelin factory hidden inside a glacier, disabling engines powered by alien crystal cores.',
	'A rogue sun sails the galaxy like a ship, crewed by beings of light who guide it between systems with solar wings.',
	'A rust-covered steam train vanishes into a canyon each full moon, returning with passengers who were never on board.',
	'A saboteur detonates a chronotronic charge inside an enemy base, freezing time long enough to steal vital war data.',
	'A saboteur sneaks through a mechanized city under blackout, planting EMP mines on patrol drones and steam sentries.',
	'A samurai standing on a misty mountain peak, his armor gleaming under the moonlight.',
	'A sentient vending machine leads a rebellion inside a future mall, recruiting appliances to fight against human neglect.',
	'A sheriff equipped with a steam-powered exosuit fights off a band of necro-bandits trying to raise a train full of corpses.',
	'A sleek mech suit, piloted by a sentient feline commander, scouts a shattered battlefield on a radioactive alien moon.',
	'A sleek, silver spacecraft breaking through the atmosphere of a gas giant, lightning crackling in the storm clouds below.',
	'A society thrives within a dark matter ring, its residents adapting to bent physics and time distortions as part of life.',
	'A space explorer discovering an ancient Earth artifact on a distant, desolate planet.',
	'A spaceship graveyard, where derelict vessels from different civilizations lie in eternal silence.',
	'A spectral gunslinger in brass armor defends a ghost town from demon rustlers, his six-shooters glowing with cold fire.',
	'A sprawling megacity twists through warped dimensions, its gravity-bending towers rotating like spirals of shattered time.',
	'A spy swaps identities using a face-shifting mask, slipping past guards into a command zeppelin hovering over Berlin.',
	'A star shaman conjures aurora spirits from an asteroid altar, casting fate into the stars with glowing cosmic dust.',
	'A starship crew in cryosleep, their pods bathed in cold blue light as the ship drifts toward an unknown destination.',
	'A steam-powered tank with tesla cannons rumbles through a shattered village, flanked by clockwork soldiers and smoke trails.',
	'A steampunk-inspired Victorian city, with airships floating above cobblestone streets.',
	'A team of astronauts exploring an alien jungle filled with bioluminescent plants and hovering jellyfish-like creatures.',
	'A technomancer opens a rift inside a crystalline reactor, unleashing wild magic into a sterile interplanetary facility.',
	'A time rift splits a Wild West town, revealing future spires and drones while cowboys face off with cybernetic sheriffs.',
	'A time-traveling pirate ship sails through cosmic wormholes, trailing solar sails and starlight behind its glowing hull.',
	'A towering zeppelin drops anti-gravity bombs over a battlefield while brass fighters duel in propeller-driven dogfights.',
	'A town built around a crashed time machine is trapped in a decade-long loop, its residents slowly remembering past lives.',
	'A town celebrates Founders Day unaware their mayor is a skinwalker who devours one citizen every year to stay in power.',
	'A trench warfare frontline sees gas-mask troops wielding magnetic rifles powered by humming reactor packs on their backs.',
	'A tribal alien ceremony unfolds beneath twin moons, with dancers painted in glowing pigments and drumming in syncopation.',
	'A warlock uses a mechanical grimoire powered by blood-coal to summon thunder spirits during an outlaw siege on his ranch.',
	'A witch rides a skeletal horse across ghost towns, harvesting the souls of those who made pacts beneath a blood moon.',
	'Allied codebreakers in a bunker race against time to decrypt enemy broadcasts sent via light-pulse morse across the sky.',
	'An Egyptian pharaoh standing atop a pyramid, overlooking his vast kingdom.',
	'An alien carnival floats in space, with gravity-bending rides and creatures offering impossible snacks that alter reality.',
	'An alien crash site lies buried beneath Monument Valley, its reactor still humming and warping time across the canyon.',
	'An alien diplomat in an ornate ceremonial robe, addressing a council of interstellar leaders.',
	'An allied commando unit parachutes behind enemy lines to sabotage a reactor-core train delivering quantum warheads.',
	'An allied pilot in brass flight armor dodges lightning harpoons while attacking a floating fortress powered by storm cores.',
	'An ancient Roman city at sunset, with markets bustling and chariots racing down cobbled streets.',
	'An ancient planet replays myths as interactive holograms, each visitor rewriting legends into new branching futures.',
	'An android orchestra performs haunting symphonies on a ruined moon, instruments built from salvage and sorrow.',
	'An asteroid-ship shaped like a dragon devours satellites for energy, its magnetic breath tearing space debris apart.',
	'An astronaut carefully tends glowing alien plants on a lonely comet garden, lit only by starlight and bioluminescence.',
	'An engineer rewires a downed mech on the battlefield while enemy drones search overhead, scanning for life and movement.',
	'An intergalactic marketplace bustling with extraterrestrial merchants selling glowing artifacts and exotic foods.',
	'An overgrown moon colony glows with bioluminescent fungi, hiding the secrets of a long-lost crew beneath spore-lit ruins.',
	'At the top of a space elevator, a zero-gravity carnival spins, offering rides that defy physics and bend time itself.',
	'Clockwork assassins infiltrate a general\'s base, disguised as servants, blades hidden inside whirring compartments.',
	'In a virtual forest of shifting trees, an ancient tree pulses with data streams, storing memories of long-deleted lives.',
	'Lightning-powered cattle stampede across a cyber-ranch, driven by electric cowboys mounted on chrome-legged velociraptors.',
	'On a crimson planet, a robotic beekeeper tends metal bees that produce data-honey from magnetic flowers in dusty valleys.',
	'On a rogue planet with glass oceans, lightning storms flash memories of extinct civilizations across the fractured sky.',
	'Reality fractures in a city center, where buildings float Escher-like and time loops trap wandering citizens forever.',
	'Secret blueprints of an enemy doomsday machine are transmitted through a telegraph hidden inside a café piano.',
	'Spy pigeons with holographic projectors carry secret messages over enemy territory in a war of signals and illusions.',
	'Steam-driven ghouls mine cursed silver in the mountains, overseen by a vampire foreman with mirrored goggles and a whip.',
	'Steam-hissing exosuits charge across no-man\'s-land, gears grinding as plasma mortars light up the fog-choked battlefield.',
	'Steam-powered artillery launches guided shells that broadcast hallucinations upon impact, disorienting enemy troops.',
	'Steam-powered dogs sniff out saboteurs trying to breach the perimeter of an airship base during a midnight lightning storm.',
	'Two gladiators clash atop a starship hull, laser blades sparking under alien constellations and the cold grip of space.',
]


/**
 * Get all prompts
 *
 * @return {Array}
 */
export const getAllPrompts = () => {
	return prompts
}


/**
 * Get random prompt
 *
 * @return {String}
 */
export const getRandomPrompt = () => {
	return getRandomValueFromArray( prompts )
}
